# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: 501c0f9ad8e516e34d5fb2cb4ec7917e0e8a18ea49b7cd387c8343bbf1a2b3e224339893df98ef88079d45ed8f4d33c0f58f91a3e8fd9fe5338827ed6406f1f2

test:
  secret_key_base: 8737d414811f9e43542d20ac6d426038c585af52065713dee4658edc3017bce57e035833d58021a896376be468198103854f40168836e61285e24df0ad780768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
